export const STARTLOADING = "STARTLOADING";
export const ENDLOADING = "ENDLOADING";
export const FETCHALLPOSTS = "FETCHALLPOSTS";
export const FETCHPOST = "FETCHPOST";
export const CREATEPOST = "CREATEPOST";
